### ISSUE TITLE
No support for commands with no arguments

### ISSUE THREAD

**Issue by NanderTGA** [its-pablo/msgroom-bot#8]
The current regex doesn't support commands without any arguments.
We should fix this.

**Comment by NanderTGA** [comment]
Oh yeah if you fix this don't commit it until we merge my changes.
We don't want to deal with merge conflicts.

**Comment by its-pablo** [comment]
your changes are merged, I will ask chatgpt to edit the regex. Thanks!

**Comment by its-pablo** [comment]
https://github.com/its-pablo/msgroom-bot/commit/1d4a950f2615cfea13438f7a67beba330ce4f3fc
done
